name: Approval Workflow

on:
  repository_dispatch:
    types: [approval-required]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
    - name: Check client payload
      id: check_payload
      run: echo "Approval message: ${{ github.event.client_payload.approval_message }}"

    - name: Manual approval
      run: |
        echo "Please manually approve this workflow run."
        exit 1
