name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  request_approval:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    

    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.S_GITHUB_TOKEN }}  # Substitua pelo seu token de acesso pessoal
        event-type: approval-required
        client-payload: '{"approval_message": "Please approve this run to continue."}'

    - name: Check approval status
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        OWNER=$(jq --raw-output .repository.owner.login "$GITHUB_EVENT_PATH")
        REPO=$(jq --raw-output .repository.name "$GITHUB_EVENT_PATH")
        
        API_RESPONSE=$(curl -X POST \
          -H "Authorization: bearer ${{ secrets.S_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.groot-preview+json" \
          -d '{"query": "query { repository(owner:\"'$OWNER'\" name:\"'$REPO'\") { pullRequest(number:'$PR_NUMBER') { reviews(first: 10) { nodes { state author { login } } } } } }"}' \
          https://api.github.com/graphql)
          
        APPROVED=$(echo $API_RESPONSE | jq '.data.repository.pullRequest.reviews.nodes[] | select(.state=="APPROVED") | .author.login')
        
        if [ -n "$APPROVED" ]; then
          echo "Approved by $APPROVED!"
        else
          echo "Not approved yet. Waiting for approval..."
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}