name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Count changes
      id: count_changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^1 HEAD | wc -l)
        echo "CHANGED_FILES=$CHANGED_FILES"
        echo "::set-output name=changed_files::$CHANGED_FILES"

    - name: Determine if approval is required
      id: approval_check
      run: |
        if [ "${{ steps.count_changes.outputs.changed_files }}" -gt 5 ]; then
          echo "approval_required=true" >> $GITHUB_ENV
        else
          echo "approval_required=false" >> $GITHUB_ENV
        fi

  request_approval:
    runs-on: ubuntu-latest
    needs: check_changes
    if: env.approval_required == 'true'
    environment:
      name: approval-required
      url: ${{ github.event.pull_request.html_url }} # Ou o URL do PR, caso exista um
    steps:
    - name: Wait for approval
      uses: hmarr/auto-approve-action@v2
      with:
        approvers: 'username1,username2'  # Substitua pelos nomes dos usuários que podem aprovar

    - name: Continue workflow after approval
      run: echo "Workflow approved. Continuing..."