name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  request_approval:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.S_GITHUB_TOKEN }}  # Substitua pelo seu token de acesso pessoal
        event-type: approval-required
        client-payload: '{"approval_message": "Please approve this run to continue."}'

  wait_for_approval:
    runs-on: ubuntu-latest
    needs: request_approval

    steps:
    - name: Wait for approval
      run: |
        echo "Waiting for approval..."
        while true; do
          # Lógica para verificar se houve aprovação manual
          # Exemplo: usar GitHub CLI para verificar comentários no PR
          sleep 60  # Aguarda 1 minuto antes de verificar novamente
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}