name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  check_inserts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Garante que temos commits suficientes para a comparação

    - name: Get previous commit SHA
      id: prev-commit
      run: echo "PREVIOUS_SHA=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

    - name: Count inserted lines
      id: count_inserts
      run: |
        PREVIOUS_SHA=${{ env.PREVIOUS_SHA }}
        CURRENT_SHA=${{ github.sha }}
        echo "Previous SHA: $PREVIOUS_SHA"
        echo "Current SHA: $CURRENT_SHA"
        INSERTED_LINES=$(git diff --numstat $PREVIOUS_SHA $CURRENT_SHA | awk '{inserted+=$1} END {print inserted}')
        echo "INSERTED_LINES=$INSERTED_LINES" >> $GITHUB_ENV

    - name: Determine if approval is required
      id: approval_check
      run: |
        if [ "${{ env.INSERTED_LINES }}" -ge 3 ]; then
          echo "review=true" >> $GITHUB_ENV
        else
          echo "review=true" >> $GITHUB_ENV
        fi

  wait_for_approval:
    runs-on: ubuntu-latest
    needs: check_inserts
    if: env.review == 'true'
    environment:
      name: requires-approval
    steps:
    - name: Approval received
      run: echo "Approval received. Continuing workflow..."