name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  check_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Obtém todo o histórico de commits

    - name: Count commits
      id: count_commits
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Commit count: $COMMIT_COUNT"
        echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV

    - name: Request approval if commits exceed limit
      if: ${{ env.COMMIT_COUNT }} >= 2  # Substitua '10' pelo limite desejado
      run: echo "Commit count is ${{ env.COMMIT_COUNT }}. Requesting approval."

  request_approval:
    runs-on: ubuntu-latest
    needs: check_commits
    if: needs.check_commits.outputs.COMMIT_COUNT && needs.check_commits.outputs.COMMIT_COUNT >= 10

    steps:
    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: approval-required
        client-payload: '{"approval_message": "Approval required for commit count: ${{ needs.check_commits.outputs.COMMIT_COUNT }}"}'

  wait_for_approval:
    runs-on: ubuntu-latest
    needs: request_approval
    if: needs.request_approval.result == 'success'

    steps:
    - name: Wait for approval
      uses: actions/manual-approval@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue: ${{ github.event.issue.number }}
        reactions: true

    - name: Approved
      run: echo "Approval received. Continuing workflow..."