name: Chamada do Workflow Integracao ECR/EB

on:
  push:
    branches:
      - main
      - feature/*
jobs:
  modulo:
    uses: gustavorsilva/modulesproject/.github/workflows/modules.yml@v1
    with:
      branch: feature/*
    secrets:
      S_GITHUB_TOKEN: ${{ secrets.S_GITHUB_TOKEN }}