name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  check_inserts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Count inserted lines
      id: count_inserts
      run: |
        PREVIOUS_SHA=$(git rev-parse HEAD^1)
        CURRENT_SHA=$(git rev-parse HEAD)
        INSERTED_LINES=$(git diff --numstat $PREVIOUS_SHA $CURRENT_SHA -- my-folder | awk '{inserted+=$1} END {print inserted}')
        echo "INSERTED_LINES=$INSERTED_LINES"
        echo "::set-output name=inserted_lines::$INSERTED_LINES"

    - name: Determine if approval is required
      id: approval_check
      run: |
        if [ "${{ steps.count_inserts.outputs.inserted_lines }}" -gt 5 ]; then
          echo "approval_required=true"
        else
          echo "approval_required=false"
        fi
    outputs:
        approval_required: ${{ steps.approval_check.outputs.approval_required }}

  request_approval:
    runs-on: ubuntu-latest
    needs: check_inserts
    if: ${{ needs.check_inserts.outputs.approval_required == 'true' }}
    steps:
    - name: Wait for approval
      uses: hmarr/auto-approve-action@v2
      with:
        approvers: 'username1,username2'  # Substitua pelos nomes dos usuários que podem aprovar

    - name: Continue workflow after approval
      run: echo "Workflow approved. Continuing..."