name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  request_approval:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    

    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.S_GITHUB_TOKEN }}  # Substitua pelo seu token de acesso pessoal
        event-type: approval-required
        client-payload: '{"approval_message": "Please approve this run to continue."}'

    - name: Check approval status
      run: |
        PR_NUMBER=$(gh pr list --state open --base main --json number --jq '.[0].number')
        gh pr merge $PR_NUMBER --auto --merge --squash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}