name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      TAG: ${{ vars.TAG }}
      STACK_NAME: ${{ vars.STACK_NAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  request_approval:
    runs-on: ubuntu-latest

    steps:
    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: approval-required
        client-payload: '{"approval_message": "Please approve this run to continue."}'

  wait_for_approval:
    runs-on: ubuntu-latest
    needs: request_approval

    steps:
    - name: Wait for approval
      run: |
        echo "Waiting for approval..."
        while true; do
          APPROVED=$(gh issue view ${{ github.run_id }} --json comments --jq '.comments[].body' | grep -i "approved" || true)
          if [ -n "$APPROVED" ]; then
            echo "Approved!"
            break
          fi
          echo "Waiting for approval..."
          sleep 60
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Continue after approval
      run: echo "Proceeding with the rest of the pipeline"