name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*
      - feature/*

jobs:
  check_inserts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Garante que temos commits suficientes para a comparação

    - name: Get previous commit SHA
      id: prev-commit
      run: echo "PREVIOUS_SHA=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

    - name: Count inserted lines
      id: count_inserts
      run: |
        PREVIOUS_SHA=${{ env.PREVIOUS_SHA }}
        CURRENT_SHA=${{ github.sha }}
        echo "Previous SHA: $PREVIOUS_SHA"
        echo "Current SHA: $CURRENT_SHA"
        INSERTED_LINES=$(git diff --numstat $PREVIOUS_SHA $CURRENT_SHA | awk '{inserted+=$1} END {print inserted}')
        echo "INSERTED_LINES=$INSERTED_LINES" >> $GITHUB_ENV
        echo "::set-output name=inserted_lines::$INSERTED_LINES"
        echo "INSERTED_LINES=$INSERTED_LINES" >> $GITHUB_ENV

    - name: Determine if approval is required
      id: approval_check
      run: |
        if [ "${{ steps.count_inserts.outputs.inserted_lines }}" -gt 5 ]; then
          echo "approval_required=true" >> $GITHUB_ENV
        else
          echo "approval_required=false"
        fi
      env:
        inserted_lines: ${{ steps.count_inserts.outputs.inserted_lines }}
    outputs:
        approval_required: ${{ env.approval_required }}

  request_approval:
    runs-on: ubuntu-latest
    needs: check_inserts
    if: ${{ needs.check_inserts.outputs.approval_required == 'true' }}
    steps:
    - name: Wait for approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: 'gustavorsilva'  # Substitua pelos nomes dos aprovadores
    - name: Continue workflow after approval
      run: echo "Workflow approved. Continuing..."