name: Chamada do Workflow Integracao ECR/EB

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  call-integracao:
    uses: gustavorsilva/modulesproject/.github/workflows/modules.yml@v1
    with:
      # Se você definiu inputs, passe os valores necessários
      branch: feature/*
    secrets:
      S_GITHUB_TOKEN: ${{ secrets.S_GITHUB_TOKEN }}