name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  request_approval:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
      
    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.S_GITHUB_TOKEN }}  # Substitua pelo seu token de acesso pessoal
        event-type: approval-required
        client-payload: '{"approval_message": "Please approve this run to continue."}'

    - name: Wait for approval
      run: |
        echo "Waiting for approval..."
        while true; do
          # Verificar se houve aprovação manual
          # Exemplo: verificar se um comentário contendo "approved" foi adicionado ao pull request
          APPROVED=$(gh pr view ${{ github.event.number }} --json comments --jq '.comments[].body' | grep -i "approved" || true)
          if [ -n "$APPROVED" ]; then
            echo "Approved!"
            break
          fi
          echo "Waiting for approval..."
          sleep 60  # Espera por 1 minuto antes de verificar novamente
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}