name: integracao-ecr-eb

on:
  push:
    branches: 
      - main
      - release/*

jobs:
  request_approval:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
    - name: Request approval
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.S_GITHUB_TOKEN }}  # Substitua pelo seu token de acesso pessoal
        event-type: approval-required
        client-payload: '{"approval_message": "Please approve this run to continue."}'

  wait_for_approval:
    runs-on: ubuntu-latest
    needs: request_approval

    steps:
    - name: Wait for approval
      run: |
        echo "Waiting for approval..."
        while true; do
          APPROVED=$(gh issue view ${{ github.run_id }} --json comments --jq '.comments[].body' | grep -i "approved" || true)
          if [ -n "$APPROVED" ]; then
            echo "Approved!"
            break
          fi
          echo "Waiting for approval..."
          sleep 60
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Continue after approval
      run: echo "Proceeding with the rest of the pipeline"